-- Update SR_ID
SELECT UpdateGeometrySRID('beach_protection','geom',3044);
SELECT UpdateGeometrySRID('buildings','geom',3044);
SELECT UpdateGeometrySRID('burial_areas','geom',3044);
SELECT UpdateGeometrySRID('coast_line_zone','geom',3044);
SELECT UpdateGeometrySRID('coast_line_zone','geom',3044);
SELECT UpdateGeometrySRID('conservation','geom',3044);
SELECT UpdateGeometrySRID('district_plan','geom',3044);
SELECT UpdateGeometrySRID('drinking_water_interests','geom',3044);
SELECT UpdateGeometrySRID('dune_conservation','geom',3044);
SELECT UpdateGeometrySRID('edge_water_stream','geom',3044);
SELECT UpdateGeometrySRID('forest','geom',3044);
SELECT UpdateGeometrySRID('forest_protection_line','geom',3044);
SELECT UpdateGeometrySRID('forest_reserve','geom',3044);
SELECT UpdateGeometrySRID('hexgrid_150','geom',3044);
SELECT UpdateGeometrySRID('lake_protection_line','geom',3044);
SELECT UpdateGeometrySRID('lakes','geom',3044);
SELECT UpdateGeometrySRID('lowlands','geom',3044);
SELECT UpdateGeometrySRID('municipality_cut_layer','geom',3044);
SELECT UpdateGeometrySRID('natura2000_bird_protection','geom',3044);
SELECT UpdateGeometrySRID('natura2000_habitat','geom',3044);
SELECT UpdateGeometrySRID('nature_and_wildlife_sanctuary','geom',3044);
SELECT UpdateGeometrySRID('nature_registration','geom',3044);
SELECT UpdateGeometrySRID('protected_ancient_sites','geom',3044);
SELECT UpdateGeometrySRID('protected_nature_types','geom',3044);
SELECT UpdateGeometrySRID('protected_stone_and_earth_dikes','geom',3044);
SELECT UpdateGeometrySRID('protected_water_streams','geom',3044);
SELECT UpdateGeometrySRID('railroad','geom',3044);
SELECT UpdateGeometrySRID('ramsar_area','geom',3044);
SELECT UpdateGeometrySRID('raw_material_sites','geom',3044);
SELECT UpdateGeometrySRID('roadsides','geom',3044);
SELECT UpdateGeometrySRID('sfl_areas','geom',3044);
SELECT UpdateGeometrySRID('stream_protection_line','geom',3044);
SELECT UpdateGeometrySRID('technical_areas','geom',3044);
SELECT UpdateGeometrySRID('v1_soil_polution','geom',3044);
SELECT UpdateGeometrySRID('v2_soil_polution','geom',3044);
SELECT UpdateGeometrySRID('wetlands','geom',3044);
SELECT UpdateGeometrySRID('wind_resource_layer','geom',3044);
SELECT UpdateGeometrySRID('wind_turbines','geom',3044);
SELECT UpdateGeometrySRID('zones_in_denmark','geom',3044);

--------------------------------------------------------------------
--|                       CREATING BUFFERS                       |--
--------------------------------------------------------------------

-- WIND TURBINE BUFFERING
-------------------------------------------------------------------

-- Buffer the wind turbines with 4 times the blade length
CREATE MATERIALIZED VIEW MV_WIND_TURBINE_BUFFER
AS
(
    SELECT  ROW_NUMBER() OVER ()::INT WTB_ID,
            IQ.GEOM
    FROM    (SELECT (ST_DUMP(ST_UNION(ST_BUFFER(WT.GEOM, CFG.BLADE_LENGTH * 4)))).GEOM
            FROM WIND_TURBINES WT, V_CONFIG CFG, MUNICIPALITY_CUT_LAYER MCL
            WHERE CFG.C_ID = 1
                AND ST_INTERSECTS(MCL.GEOM, WT.GEOM)
        ) AS IQ
    -- IQ = Inner Query
)
WITH DATA;


-- Index MV_WIND_TURBINE_BUFFER
CREATE INDEX MV_GIX_WIND_TUBRINE_BUFFER
ON MV_WIND_TURBINE_BUFFER
USING GIST (GEOM);


-- STATE ROAD BUFFERING
-------------------------------------------------------------------
CREATE MATERIALIZED VIEW MV_STATE_ROAD_BUFFER
AS
(
    SELECT  ROW_NUMBER() OVER ()::INT SRB_ID,
        ST_Buffer(STATE_ROADS.GEOM, 250) GEOM
    FROM STATE_ROADS, MUNICIPALITY_CUT_LAYER MCL
        WHERE ST_INTERSECTS(MCL.GEOM, STATE_ROADS.GEOM)
)
WITH DATA;


-- Index MV_STATE_ROAD_BUFFER
CREATE INDEX MV_GIX_STATE_ROAD_BUFFER
ON MV_STATE_ROAD_BUFFER
USING GIST (GEOM);

-- RAILROAD BUFFERING
-------------------------------------------------------------------
CREATE MATERIALIZED VIEW MV_RAILROAD_BUFFER
AS
(
    SELECT  ROW_NUMBER() OVER ()::INT AS RFB_ID,
        ST_BUFFER(RAILROAD.GEOM, 250) GEOM
    FROM RAILROAD, MUNICIPALITY_CUT_LAYER MCL
        WHERE ST_INTERSECTS(MCL.GEOM, RAILROAD.GEOM)
)
WITH DATA;

CREATE INDEX MV_GIX_RAILROAD_BUFFER
ON MV_RAILROAD_BUFFER
USING GIST (GEOM);


-- RESIDENTIAL AREA BUFFERING
-------------------------------------------------------------------
CREATE MATERIALIZED VIEW MV_BUILDINGS_BUFFER
AS
(
    SELECT ROW_NUMBER() OVER ()::INT AS BB_ID,
        ST_UNION(ST_BUFFER(B.GEOM, CFG.WT_HEIGHT * 4)) AS GEOM
    FROM BUILDINGS B
        JOIN MUNICIPALITY_CUT_LAYER MCL
            ON ST_INTERSECTS(B.GEOM, MCL.GEOM)
        JOIN V_CONFIG CFG
            ON CFG.C_ID = 1
        INNER JOIN BUILDING_META BM
            ON ST_INTERSECTS(B.GEOM, BM.GEOM)
                AND BM.BYG_ANVEND IN (110, 120, 130, 140, 150, 160, 190, 510, 520, 530, 540, 550)
    -- CODES FOR BUILDING USE
    -- SOURCE: HTTP://BBR.DK/BYG-ANVENDELSE/0/30 
)
WITH DATA;

CREATE INDEX MV_GIX_BUILDINGS_BUFFER
ON MV_BUILDINGS_BUFFER
USING GIST (GEOM);

-- CREATE MERGED RESTRICTIVE BUFFER ZONE
CREATE MATERIALIZED VIEW MV_PRE_MERGED_RESTRICTIVE_BUFFER
AS
(
    SELECT ST_BUFFER(
        ST_COLLECT(
            ARRAY(
                SELECT ST_FORCE2D(GEOM)
                    FROM MV_WIND_TURBINE_BUFFER
                    
                UNION SELECT ST_FORCE2D(GEOM)
                    FROM MV_BUILDINGS_BUFFER
                    
                UNION SELECT ST_FORCE2D(GEOM)
                    FROM MV_STATE_ROAD_BUFFER
                    
                UNION SELECT ST_FORCE2D(GEOM)
                    FROM MV_RAILROAD_BUFFER    
                                                                                           
                UNION SELECT ST_FORCE2D(GEOM)
                    FROM PROTECTED_NATURE_TYPES
                                        
                UNION SELECT ST_FORCE2D(RA.GEOM)
                    FROM RAMSAR_AREA RA
                        INNER JOIN MUNICIPALITY_CUT_LAYER MCL
                            ON ST_INTERSECTS(MCL.GEOM, RA.GEOM)
                            
                UNION SELECT ST_FORCE2D(FR.GEOM)
                    FROM FOREST_RESERVE FR
                        INNER JOIN MUNICIPALITY_CUT_LAYER MCL
                            ON ST_INTERSECTS(MCL.GEOM, FR.GEOM)               
                
                UNION SELECT ST_FORCE2D(DC.GEOM)
                    FROM DUNE_CONSERVATION DC
                        INNER JOIN MUNICIPALITY_CUT_LAYER MCL
                            ON ST_INTERSECTS(MCL.GEOM, DC.GEOM)
                
                UNION SELECT ST_FORCE2D(BA.GEOM)
                    FROM BURIAL_AREAS BA
                        INNER JOIN MUNICIPALITY_CUT_LAYER MCL
                            ON ST_INTERSECTS(MCL.GEOM, BA.GEOM)
                
                UNION SELECT ST_FORCE2D(PAS.GEOM)
                    FROM PROTECTED_ANCIENT_SITES PAS
                        INNER JOIN MUNICIPALITY_CUT_LAYER MCL
                            ON ST_INTERSECTS(MCL.GEOM, PAS.GEOM)
                
                UNION SELECT ST_FORCE2D(CSV.GEOM)
                    FROM CONSERVATION CSV
                        INNER JOIN MUNICIPALITY_CUT_LAYER MCL
                            ON ST_INTERSECTS(MCL.GEOM, CSV.GEOM)
                            
                UNION SELECT ST_FORCE2D(NBP.GEOM)
                    FROM NATURA2000_BIRD_PROTECTION NBP
                        INNER JOIN MUNICIPALITY_CUT_LAYER MCL
                            ON ST_INTERSECTS(MCL.GEOM, NBP.GEOM)
                            
                UNION SELECT ST_FORCE2D(NH.GEOM)
                    FROM NATURA2000_HABITAT NH
                        INNER JOIN MUNICIPALITY_CUT_LAYER MCL
                            ON ST_INTERSECTS(MCL.GEOM, NH.GEOM)
                            
                UNION SELECT ST_FORCE2D(NAWS.GEOM)
                    FROM NATURE_AND_WILDLIFE_SANCTUARY NAWS
                        INNER JOIN MUNICIPALITY_CUT_LAYER MCL
                            ON ST_INTERSECTS(MCL.GEOM, NAWS.GEOM)
                            
                UNION SELECT ST_FORCE2D(NR.GEOM)
                    FROM NATURE_REGISTRATION NR
                        INNER JOIN MUNICIPALITY_CUT_LAYER MCL
                            ON ST_INTERSECTS(MCL.GEOM, NR.GEOM)
                
                UNION SELECT ST_FORCE2D(PWS.GEOM)               
                    FROM PROTECTED_WATER_STREAMS PWS
                        INNER JOIN MUNICIPALITY_CUT_LAYER MCL
                            ON ST_INTERSECTS(MCL.GEOM, PWS.GEOM)
                
                UNION SELECT ST_FORCE2D(EWS.GEOM)               
                    FROM EDGE_WATER_STREAM EWS
                        INNER JOIN MUNICIPALITY_CUT_LAYER MCL
                            ON ST_INTERSECTS(MCL.GEOM, EWS.GEOM)
                
                UNION SELECT ST_FORCE2D(FOREST.GEOM)               
                    FROM FOREST
                        INNER JOIN MUNICIPALITY_CUT_LAYER MCL
                            ON ST_INTERSECTS(MCL.GEOM, FOREST.GEOM)
                
                UNION SELECT ST_FORCE2D(LAKES.GEOM)               
                    FROM LAKES
                        INNER JOIN MUNICIPALITY_CUT_LAYER MCL
                            ON ST_INTERSECTS(MCL.GEOM, LAKES.GEOM)
                
                UNION SELECT ST_FORCE2D(RS.GEOM)               
                    FROM ROADSIDES RS
                        INNER JOIN MUNICIPALITY_CUT_LAYER MCL
                            ON ST_INTERSECTS(MCL.GEOM, RS.GEOM)
            )
        ),
    0) AS GEOM
)
WITH DATA;

-- CREATE FINAL MERGED RESTRICTIVE BUFFER ZONE CUT TO MUNICIPALITY BORDERS
CREATE MATERIALIZED VIEW MV_MERGED_RESTRICTIVE_BUFFER
AS
(
    SELECT ROW_NUMBER() OVER ()::INT AS RB_ID,
        ST_BUFFER(ST_INTERSECTION(ST_FORCE2D(MCL.GEOM), ST_FORCE2D(MVPMRB.GEOM)), 0) AS GEOM
    FROM MUNICIPALITY_CUT_LAYER MCL,
        MV_PRE_MERGED_RESTRICTIVE_BUFFER MVPMRB
)
WITH DATA;

--------------------------------------------------------------------
--|       DEDUCT FINAL RESTRICTIVE LAYER FROM OTHER LAYERS       |--
--------------------------------------------------------------------

CREATE MATERIALIZED VIEW MV_CHURCH_PROTECTION_LINE
AS
(
    SELECT ROW_NUMBER() OVER ()::INT AS CPL_ID,
           ST_DIFFERENCE(ST_INTERSECTION(CPL.GEOM, MCL.GEOM), MVMRB.GEOM) AS GEOM
        FROM CHURCH_PROTECTION_LINE CPL,
            MUNICIPALITY_CUT_LAYER MCL,
            MV_MERGED_RESTRICTIVE_BUFFER MVMRB
)
WITH DATA;

CREATE INDEX MV_GIX_CHURCH_PROTECTION_LINE
ON MV_CHURCH_PROTECTION_LINE
USING GIST (GEOM);


CREATE MATERIALIZED VIEW MV_COAST_LINE_ZONE
AS
(
    SELECT ROW_NUMBER() OVER ()::INT AS CLZ_ID,
           ST_DIFFERENCE(ST_INTERSECTION(CLZ.GEOM, MCL.GEOM), MVMRB.GEOM) AS GEOM
        FROM COAST_LINE_ZONE CLZ,
            MUNICIPALITY_CUT_LAYER MCL,
            MV_MERGED_RESTRICTIVE_BUFFER MVMRB
)
WITH DATA;

CREATE INDEX MV_GIX_COAST_LINE_ZONE
ON MV_COAST_LINE_ZONE
USING GIST (GEOM);


-- Creating new column to host corrected data
ALTER TABLE FOREST_PROTECTION_LINE
ADD COLUMN GEOM_MP GEOMETRY(MULTIPOLYGONZ, 3044);

UPDATE FOREST_PROTECTION_LINE
SET GEOM_MP = ST_MULTI(ST_BUFFER(GEOM, 0));

ALTER TABLE FOREST_PROTECTION_LINE
DROP COLUMN GEOM;

ALTER TABLE FOREST_PROTECTION_LINE
RENAME COLUMN GEOM_MP TO GEOM;

CREATE MATERIALIZED VIEW MV_FOREST_PROTECTION_LINE
AS
(
    SELECT ROW_NUMBER() OVER ()::INT AS FPL_ID,
           ST_DIFFERENCE(ST_INTERSECTION(FPL.GEOM, MCL.GEOM), MVMRB.GEOM) AS GEOM
        FROM FOREST_PROTECTION_LINE FPL,
            MUNICIPALITY_CUT_LAYER MCL,
            MV_MERGED_RESTRICTIVE_BUFFER MVMRB
)
WITH DATA;

CREATE INDEX MV_GIX_FOREST_PROTECTION_LINE
ON MV_FOREST_PROTECTION_LINE
USING GIST (GEOM);


CREATE MATERIALIZED VIEW MV_LAKE_PROTECTION_LINE
AS
(
    SELECT ROW_NUMBER() OVER ()::INT AS LPL_ID,
           ST_DIFFERENCE(ST_INTERSECTION(LPL.GEOM, MCL.GEOM), MVMRB.GEOM) AS GEOM
        FROM LAKE_PROTECTION_LINE LPL,
            MUNICIPALITY_CUT_LAYER MCL,
            MV_MERGED_RESTRICTIVE_BUFFER MVMRB
)
WITH DATA;

CREATE INDEX MV_GIX_LAKE_PROTECTION_LINE
ON MV_LAKE_PROTECTION_LINE
USING GIST (GEOM);


CREATE MATERIALIZED VIEW MV_LOWLANDS
AS
(
    SELECT ROW_NUMBER() OVER ()::INT AS LL_ID,
           ST_DIFFERENCE(ST_INTERSECTION(ST_BUFFER(LL.GEOM, 0), ST_BUFFER(MCL.GEOM, 0)), MVMRB.GEOM) AS GEOM
        FROM LOWLANDS LL,
            MUNICIPALITY_CUT_LAYER MCL,
            MV_MERGED_RESTRICTIVE_BUFFER MVMRB
)
WITH DATA;

CREATE INDEX MV_GIX_LOWLANDS
ON MV_LOWLANDS
USING GIST (GEOM);


CREATE MATERIALIZED VIEW MV_PROTECTED_EARTH_STONE_DIKES
AS
(
    SELECT ROW_NUMBER() OVER ()::INT AS PESD_ID,
           ST_DIFFERENCE(ST_INTERSECTION(PESD.GEOM, MCL.GEOM), MVMRB.GEOM) AS GEOM
        FROM PROTECTED_EARTH_STONE_DIKES PESD,
            MUNICIPALITY_CUT_LAYER MCL,
            MV_MERGED_RESTRICTIVE_BUFFER MVMRB
)
WITH DATA;

CREATE INDEX MV_GIX_PROTECTED_EARTH_STONE_DIKES
ON MV_PROTECTED_EARTH_STONE_DIKES
USING GIST (GEOM);


CREATE MATERIALIZED VIEW MV_STREAM_PROTECTION_LINE
AS
(
    SELECT ROW_NUMBER() OVER ()::INT AS SPL_ID,
           ST_DIFFERENCE(ST_INTERSECTION(SPL.GEOM, MCL.GEOM), MVMRB.GEOM) AS GEOM
        FROM STREAM_PROTECTION_LINE SPL,
            MUNICIPALITY_CUT_LAYER MCL,
            MV_MERGED_RESTRICTIVE_BUFFER MVMRB
)
WITH DATA;

CREATE INDEX MV_GIX_STREAM_PROTECTION_LINE
ON MV_STREAM_PROTECTION_LINE
USING GIST (GEOM);


CREATE MATERIALIZED VIEW MV_V2_SOIL_POLUTION
AS
(
    SELECT ROW_NUMBER() OVER ()::INT AS V2SP_ID,
           ST_DIFFERENCE(ST_INTERSECTION(V2SP.GEOM, MCL.GEOM), MVMRB.GEOM) AS GEOM
        FROM V2_SOIL_POLUTION V2SP,
            MUNICIPALITY_CUT_LAYER MCL,
            MV_MERGED_RESTRICTIVE_BUFFER MVMRB
)
WITH DATA;

CREATE INDEX MV_GIX_V2_SOIL_POLUTION
ON MV_V2_SOIL_POLUTION
USING GIST (GEOM);


CREATE MATERIALIZED VIEW MV_WETLANDS
AS
(
    SELECT ROW_NUMBER() OVER ()::INT AS WL_ID,
           ST_DIFFERENCE(ST_INTERSECTION(WL.GEOM, MCL.GEOM), MVMRB.GEOM) AS GEOM
        FROM WETLANDS WL,
            MUNICIPALITY_CUT_LAYER MCL,
            MV_MERGED_RESTRICTIVE_BUFFER MVMRB
)
WITH DATA;

CREATE INDEX MV_GIX_WETLANDS
ON MV_WETLANDS
USING GIST (GEOM);


CREATE MATERIALIZED VIEW MV_BEACH_PROTECTION
AS
(
    SELECT ROW_NUMBER() OVER ()::INT AS BP_ID,
           ST_DIFFERENCE(ST_INTERSECTION(BP.GEOM, MCL.GEOM), MVMRB.GEOM) AS GEOM
        FROM BEACH_PROTECTION BP,
            MUNICIPALITY_CUT_LAYER MCL,
            MV_MERGED_RESTRICTIVE_BUFFER MVMRB
)
WITH DATA;

CREATE INDEX MV_GIX_BEACH_PROTECTION
ON MV_BEACH_PROTECTION
USING GIST (GEOM);


-- Distinguish buffers with more than 3 wind turbines in them
-- define that as a wind site
CREATE VIEW V_WIND_TURBINE_SITES
AS
(
    SELECT MV_WTB.WTB_ID, MV_WTB.GEOM, COUNT(WT.GID) WT_CNT
    FROM  MV_WIND_TURBINE_BUFFER MV_WTB
        CROSS JOIN WIND_TURBINES WT
    WHERE ST_INTERSECTS(WT.GEOM, MV_WTB.GEOM)
    GROUP BY WTB_ID, MV_WTB.GEOM
        HAVING COUNT(WT.GID) > 3
    ORDER BY WT_CNT DESC
);

-- Buffer the wind turbine sites with buffer size 28 times the heigth of turbine
CREATE MATERIALIZED VIEW MV_WIND_TURBINE_SITE_BUFFER
AS
(
    SELECT  ROW_NUMBER() OVER ()::INT WTSB_ID,
            ST_DIFFERENCE(ST_INTERSECTION(IQ.GEOM, MCL.GEOM), MVMRB.GEOM) AS GEOM
    FROM    (SELECT (ST_DUMP(ST_UNION(ST_BUFFER(WT.GEOM, CFG.WT_HEIGHT * 28)))).GEOM
             FROM     WIND_TURBINES WT
                JOIN V_WIND_TURBINE_SITES V_WTS
                    ON ST_INTERSECTS(WT.GEOM, V_WTS.GEOM)
                JOIN V_CONFIG CFG
                    ON CFG.C_ID = 1
            ) AS IQ,
            MUNICIPALITY_CUT_LAYER MCL,
            MV_MERGED_RESTRICTIVE_BUFFER MVMRB
    -- IQ = Inner Query
)
WITH DATA;

-- Index MV_WIND_TURBINE_SITE_BUFFER
CREATE INDEX MV_GIX_WIND_TURBINE_SITE_BUFFER
ON MV_WIND_TURBINE_SITE_BUFFER
USING GIST (GEOM);


-- MUNICIPALITY ROADS
-------------------------------------------------------------------
CREATE MATERIALIZED VIEW MV_MUNICIPALITY_ROAD_BUFFER
AS
(
    SELECT  ROW_NUMBER() OVER ()::INT AS MRB_ID,
            ST_DIFFERENCE(ST_BUFFER(ST_INTERSECTION(MR.GEOM, MCL.GEOM), 250), MVMRB.GEOM) AS GEOM
    FROM MUNICIPALITY_ROADS MR,
         MUNICIPALITY_CUT_LAYER MCL,
         MV_MERGED_RESTRICTIVE_BUFFER MVMRB
    WHERE MR.VEJSTATUS = 'Offentlig'
)
WITH DATA;

CREATE INDEX MV_GIX_MUNICIPALITY_ROAD_BUFFER
ON MV_MUNICIPALITY_ROAD_BUFFER
USING GIST (GEOM);


CREATE MATERIALIZED VIEW MV_RAW_MATERIAL_SITES
AS
(
    SELECT ROW_NUMBER() OVER ()::INT AS RMS_ID,
           ST_DIFFERENCE(ST_INTERSECTION(RMS.GEOM, MCL.GEOM), MVMRB.GEOM) AS GEOM
        FROM RAW_MATERIAL_SITES RMS,
            MUNICIPALITY_CUT_LAYER MCL,
            MV_MERGED_RESTRICTIVE_BUFFER MVMRB
)
WITH DATA;

CREATE INDEX MV_GIX_RAW_MATERIAL_SITES
ON MV_RAW_MATERIAL_SITES
USING GIST (GEOM);

-- Fix invalid geometries
UPDATE DISTRICT_PLAN
SET GEOM = ST_MULTI(ST_BUFFER(GEOM, 0));

CREATE MATERIALIZED VIEW MV_DISTRICT_PLAN
AS
(
    SELECT ROW_NUMBER() OVER ()::INT AS DP_ID,
           ST_DIFFERENCE(ST_INTERSECTION(DP.GEOM, MCL.GEOM), MVMRB.GEOM) AS GEOM
        FROM DISTRICT_PLAN DP,
            MUNICIPALITY_CUT_LAYER MCL,
            MV_MERGED_RESTRICTIVE_BUFFER MVMRB
)
WITH DATA;

CREATE INDEX MV_GIX_DISTRICT_PLAN
ON MV_DISTRICT_PLAN
USING GIST (GEOM);


CREATE MATERIALIZED VIEW MV_V1_SOIL_POLUTION
AS
(
    SELECT ROW_NUMBER() OVER ()::INT AS V1SP_ID,
           ST_DIFFERENCE(ST_INTERSECTION(V1SP.GEOM, MCL.GEOM), MVMRB.GEOM) AS GEOM
        FROM V1_SOIL_POLUTION V1SP,
            MUNICIPALITY_CUT_LAYER MCL,
            MV_MERGED_RESTRICTIVE_BUFFER MVMRB
)
WITH DATA;

CREATE INDEX MV_GIX_V1_SOIL_POLUTION
ON MV_V1_SOIL_POLUTION
USING GIST (GEOM);


CREATE MATERIALIZED VIEW MV_DRINKING_WATER_INTEREST
AS
(
    SELECT ROW_NUMBER() OVER ()::INT AS DWI_ID,
           ST_DIFFERENCE(ST_INTERSECTION(DWI.GEOM, MCL.GEOM), MVMRB.GEOM) AS GEOM
        FROM DRINKING_WATER_INTEREST DWI,
            MUNICIPALITY_CUT_LAYER MCL,
            MV_MERGED_RESTRICTIVE_BUFFER MVMRB
)
WITH DATA;

CREATE INDEX MV_GIX_DRINKING_WATER_INTEREST
ON MV_DRINKING_WATER_INTEREST
USING GIST (GEOM);


CREATE MATERIALIZED VIEW MV_TECHNICAL_AREAS
AS
(
    SELECT ROW_NUMBER() OVER ()::INT AS TA_ID,
           ST_DIFFERENCE(ST_INTERSECTION(TA.GEOM, MCL.GEOM), MVMRB.GEOM) AS GEOM
        FROM TECHNICAL_AREAS TA,
            MUNICIPALITY_CUT_LAYER MCL,
            MV_MERGED_RESTRICTIVE_BUFFER MVMRB
)
WITH DATA;

CREATE INDEX MV_GIX_TECHNICAL_AREAS
ON MV_TECHNICAL_AREAS
USING GIST (GEOM);

--TODO make wind map layer

--------------------------------------------------------------------
--|                GRID RATIO VALUE CALCULATING                  |--
--------------------------------------------------------------------

--                      DERIVED BUFFER ZONES                      --
--------------------------------------------------------------------

-- Finding wind turbine ratio values
ALTER TABLE HEXGRID_150
ADD COLUMN WIND_TURBINE_RATIO
NUMERIC NOT NULL DEFAULT 1;

UPDATE HEXGRID_150
    SET WIND_TURBINE_RATIO = IQ.PRCNT
    FROM (SELECT HG.GID ID,
            1 - ROUND(CAST(FLOAT8(ST_AREA(ST_UNION(ST_INTERSECTION(MVWTB.GEOM, HG.GEOM))) / HG.SHAPE_AREA) AS NUMERIC), 6) PRCNT
        FROM     HEXGRID_150 HG,
            MV_WIND_TURBINE_BUFFER MVWTB
        WHERE ST_INTERSECTS(HG.GEOM, MVWTB.GEOM)
            GROUP BY HG.GID, HG.SHAPE_AREA) AS IQ
WHERE HEXGRID_150.GID = IQ.ID;


-- Finding wind turbine site ratio values
ALTER TABLE HEXGRID_150
ADD COLUMN WIND_TURBINE_SITE_RATIO
NUMERIC NOT NULL DEFAULT 1;

UPDATE HEXGRID_150
    SET WIND_TURBINE_SITE_RATIO = IQ.PRCNT
    FROM (SELECT HG.GID ID,
            1 - ROUND(CAST(FLOAT8(ST_AREA(ST_UNION(ST_INTERSECTION(MVWTSB.GEOM, HG.GEOM))) / HG.SHAPE_AREA) AS NUMERIC), 6) PRCNT
        FROM     HEXGRID_150 HG,
            MV_WIND_TURBINE_SITE_BUFFER MVWTSB
        WHERE ST_INTERSECTS(HG.GEOM, MVWTSB.GEOM)
            GROUP BY HG.GID, HG.SHAPE_AREA) AS IQ
WHERE HEXGRID_150.GID = IQ.ID;


-- Finding state road ratio values
ALTER TABLE HEXGRID_150
ADD COLUMN STATE_ROAD_RATIO
NUMERIC NOT NULL DEFAULT 1;

UPDATE HEXGRID_150
    SET STATE_ROAD_RATIO = IQ.PRCNT
    FROM (SELECT HG.GID ID,
            1 - ROUND(CAST(FLOAT8(ST_AREA(ST_UNION(ST_INTERSECTION(MVSRB.GEOM, HG.GEOM))) / HG.SHAPE_AREA) AS NUMERIC), 6) PRCNT
        FROM     HEXGRID_150 HG,
            MV_STATE_ROAD_BUFFER MVSRB
        WHERE ST_INTERSECTS(HG.GEOM, MVSRB.GEOM)
            GROUP BY HG.GID, HG.SHAPE_AREA) AS IQ
WHERE HEXGRID_150.GID = IQ.ID;


-- Finding municipality road ratio values
ALTER TABLE HEXGRID_150
ADD COLUMN MUNICIPALITY_ROAD_RATIO
NUMERIC NOT NULL DEFAULT 1;

UPDATE HEXGRID_150
    SET MUNICIPALITY_ROAD_RATIO = IQ.PRCNT
    FROM (SELECT HG.GID ID,
            1 - ROUND(CAST(FLOAT8(ST_AREA(ST_UNION(ST_INTERSECTION(MVMRB.GEOM, HG.GEOM))) / HG.SHAPE_AREA) AS NUMERIC), 6) PRCNT
        FROM     HEXGRID_150 HG,
            MV_MUNICIPALITY_ROAD_BUFFER MVMRB
        WHERE ST_INTERSECTS(HG.GEOM, MVMRB.GEOM)
            GROUP BY HG.GID, HG.SHAPE_AREA) AS IQ
WHERE HEXGRID_150.GID = IQ.ID;


-- Finding railroad ratio values
ALTER TABLE HEXGRID_150
ADD COLUMN RAILROAD_RATIO
NUMERIC NOT NULL DEFAULT 1;

UPDATE HEXGRID_150
    SET RAILROAD_RATIO = IQ.PRCNT
    FROM (SELECT HG.GID ID,
            1 - ROUND(CAST(FLOAT8(ST_AREA(ST_UNION(ST_INTERSECTION(MVRB.GEOM, HG.GEOM))) / HG.SHAPE_AREA) AS NUMERIC), 6) PRCNT
        FROM     HEXGRID_150 HG,
            MV_RAILROAD_BUFFER MVRB
        WHERE ST_INTERSECTS(HG.GEOM, MVRB.GEOM)
            GROUP BY HG.GID, HG.SHAPE_AREA) AS IQ
WHERE HEXGRID_150.GID = IQ.ID;

--                          OTHER LAYERS                          --
--------------------------------------------------------------------

-- Finding beach protection ratio values
ALTER TABLE HEXGRID_150
ADD COLUMN BEACH_PROTECTION_RATIO
NUMERIC NOT NULL DEFAULT 1;

UPDATE HEXGRID_150
    SET BEACH_PROTECTION_RATIO = IQ.PRCNT
    FROM    (SELECT    HG.GID ID,
            1 - ROUND(CAST(FLOAT8(ST_AREA(ST_UNION(ST_INTERSECTION(MVBP.GEOM, HG.GEOM))) / HG.SHAPE_AREA) AS NUMERIC), 6) PRCNT
        FROM     HEXGRID_150 HG,
            MV_BEACH_PROTECTION MVBP
        WHERE ST_INTERSECTS(HG.GEOM, MVBP.GEOM)
            GROUP BY HG.GID, HG.SHAPE_AREA) AS IQ
WHERE HEXGRID_150.GID = IQ.ID;


-- Finding building buffer ratio values
ALTER TABLE HEXGRID_150
ADD COLUMN BUILDING_RATIO
NUMERIC NOT NULL DEFAULT 1;

UPDATE HEXGRID_150
    SET BUILDING_RATIO = IQ.PRCNT
    FROM (    SELECT HG.GID ID,
        1 - ROUND(CAST(FLOAT8(ST_AREA(ST_UNION(ST_INTERSECTION(MVBB.GEOM, HG.GEOM))) / HG.SHAPE_AREA) AS NUMERIC), 6) PRCNT
        FROM MV_BUILDINGS_BUFFER MVBB
            JOIN HEXGRID_150 HG
                ON ST_INTERSECTS(HG.GEOM, MVBB.GEOM)
        GROUP BY HG.GID, HG.SHAPE_AREA) AS IQ
WHERE HEXGRID_150.GID = IQ.ID;


-- FINDING BURIAL AREA RATIO VALUES
ALTER TABLE HEXGRID_150
ADD COLUMN BURIAL_AREA_RATIO
NUMERIC NOT NULL DEFAULT 1;

UPDATE HEXGRID_150
    SET BURIAL_AREA_RATIO = IQ.PRCNT
    FROM (    SELECT     HG.GID ID,
        1 - ROUND(CAST(FLOAT8(ST_AREA(ST_UNION(ST_INTERSECTION(BA.GEOM, HG.GEOM))) / HG.SHAPE_AREA) AS NUMERIC), 6) PRCNT
        FROM HEXGRID_150 HG
            JOIN BURIAL_AREAS BA
                ON ST_INTERSECTS(HG.GEOM, BA.GEOM)
        GROUP BY HG.GID, HG.SHAPE_AREA) AS IQ
WHERE HEXGRID_150.GID = IQ.ID;


-- Finding church protection line ratio
ALTER TABLE HEXGRID_150
ADD COLUMN CHURCH_PROTECTION_LINE_RATIO
NUMERIC NOT NULL DEFAULT 1;

UPDATE HEXGRID_150
    SET CHURCH_PROTECTION_LINE_RATIO = IQ.PRCNT
    FROM (    SELECT     HG.GID ID,
        1 - ROUND(CAST(FLOAT8(ST_AREA(ST_UNION(ST_INTERSECTION(MVCPL.GEOM, HG.GEOM))) / HG.SHAPE_AREA) AS NUMERIC), 6) PRCNT
        FROM HEXGRID_150 HG
            JOIN MV_CHURCH_PROTECTION_LINE MVCPL
                ON ST_INTERSECTS(HG.GEOM, MVCPL.GEOM)
        GROUP BY HG.GID, HG.SHAPE_AREA) AS IQ
WHERE HEXGRID_150.GID = IQ.ID;


-- FINDING COAST LINE RATIO VALUES
ALTER TABLE HEXGRID_150
ADD COLUMN COAST_LINE_ZONE_RATIO
NUMERIC NOT NULL DEFAULT 1;

UPDATE HEXGRID_150
    SET COAST_LINE_ZONE_RATIO = IQ.PRCNT
    FROM (    SELECT     HG.GID ID,
        1 - ROUND(CAST(FLOAT8(ST_AREA(ST_UNION(ST_INTERSECTION(MVCLZ.GEOM, HG.GEOM))) / HG.SHAPE_AREA) AS NUMERIC), 6) PRCNT
        FROM HEXGRID_150 HG
            JOIN MV_COAST_LINE_ZONE MVCLZ
                ON ST_INTERSECTS(HG.GEOM, MVCLZ.GEOM)
        GROUP BY HG.GID, HG.SHAPE_AREA) AS IQ
WHERE HEXGRID_150.GID = IQ.ID;


-- Finding conservation ratio
ALTER TABLE HEXGRID_150
ADD COLUMN CONSERVATION_RATIO
NUMERIC NOT NULL DEFAULT 1;

-- FINDING CONSERVATION RATIO VALUES
UPDATE HEXGRID_150
    SET CONSERVATION_RATIO = IQ.PRCNT
    FROM (    SELECT     HG.GID ID,
        1 - ROUND(CAST(FLOAT8(ST_AREA(ST_UNION(ST_INTERSECTION(C.GEOM, HG.GEOM))) / HG.SHAPE_AREA) AS NUMERIC), 6) PRCNT
        FROM HEXGRID_150 HG
            JOIN CONSERVATION C
                ON ST_INTERSECTS(HG.GEOM, C.GEOM)
        GROUP BY HG.GID, HG.SHAPE_AREA) AS IQ
WHERE HEXGRID_150.GID = IQ.ID;


-- Finding drinking water interest ratio
ALTER TABLE HEXGRID_150
ADD COLUMN DRINKING_WATER_INTEREST_RATIO
NUMERIC NOT NULL DEFAULT 1;

UPDATE HEXGRID_150
    SET DRINKING_WATER_INTEREST_RATIO = IQ.PRCNT
    FROM (    SELECT     HG.GID ID,
        1 - ROUND(CAST(FLOAT8(ST_AREA(ST_UNION(ST_INTERSECTION(MVDWI.GEOM, HG.GEOM))) / HG.SHAPE_AREA) AS NUMERIC), 6) PRCNT
        FROM HEXGRID_150 HG
            JOIN MV_DRINKING_WATER_INTERESTS MVDWI
                ON ST_INTERSECTS(HG.GEOM, MVDWI.GEOM)
        GROUP BY HG.GID, HG.SHAPE_AREA) AS IQ
WHERE HEXGRID_150.GID = IQ.ID;


-- Finding dune conservation ratio value
ALTER TABLE HEXGRID_150
ADD COLUMN DUNE_CONSERVATION_RATIO
NUMERIC NOT NULL DEFAULT 1;

UPDATE HEXGRID_150
    SET DUNE_CONSERVATION_RATIO = IQ.PRCNT
    FROM (    SELECT     HG.GID ID,
            1 - ROUND(CAST(FLOAT8(ST_AREA(ST_UNION(ST_INTERSECTION(DC.GEOM, HG.GEOM))) / HG.SHAPE_AREA) AS NUMERIC), 6) PRCNT
        FROM HEXGRID_150 HG
            JOIN DUNE_CONSERVATION DC
                ON ST_INTERSECTS(HG.GEOM, DC.GEOM)
        GROUP BY HG.GID, HG.SHAPE_AREA) AS IQ
WHERE HEXGRID_150.GID = IQ.ID;


-- Finding edge water stream ratio value
ALTER TABLE HEXGRID_150
ADD COLUMN EDGE_WATER_STREAM_RATIO
NUMERIC NOT NULL DEFAULT 1;

UPDATE HEXGRID_150
    SET EDGE_WATER_STREAM_RATIO = IQ.PRCNT
    FROM (    SELECT     HG.GID ID,
            1 - ROUND(CAST(FLOAT8(ST_AREA(ST_UNION(ST_INTERSECTION(EWS.GEOM, HG.GEOM))) / HG.SHAPE_AREA) AS NUMERIC), 6) PRCNT
        FROM HEXGRID_150 HG
            JOIN EDGE_WATER_STREAM EWS
                ON ST_INTERSECTS(HG.GEOM, EWS.GEOM)
        GROUP BY HG.GID, HG.SHAPE_AREA) AS IQ
WHERE HEXGRID_150.GID = IQ.ID;


-- Finding forest ratio value
ALTER TABLE HEXGRID_150
ADD COLUMN FOREST_RATIO
NUMERIC NOT NULL DEFAULT 1;

UPDATE HEXGRID_150
    SET FOREST_RATIO = IQ.PRCNT
    FROM (    SELECT     HG.GID ID,
            1 - ROUND(CAST(FLOAT8(ST_AREA(ST_UNION(ST_INTERSECTION(FOREST.GEOM, HG.GEOM))) / HG.SHAPE_AREA) AS NUMERIC), 6) PRCNT
        FROM HEXGRID_150 HG
            JOIN FOREST
                ON ST_INTERSECTS(HG.GEOM, FOREST.GEOM)
        GROUP BY HG.GID, HG.SHAPE_AREA) AS IQ
WHERE HEXGRID_150.GID = IQ.ID;


-- Finding forest reserve ratio value
ALTER TABLE HEXGRID_150
ADD COLUMN FOREST_RESERVE_RATIO
NUMERIC NOT NULL DEFAULT 1;

UPDATE HEXGRID_150
    SET FOREST_RESERVE_RATIO = IQ.PRCNT
    FROM (    SELECT     HG.GID ID,
            1 - ROUND(CAST(FLOAT8(ST_AREA(ST_UNION(ST_INTERSECTION(FR.GEOM, HG.GEOM))) / HG.SHAPE_AREA) AS NUMERIC), 6) PRCNT
        FROM HEXGRID_150 HG
            JOIN FOREST_RESERVE FR
                ON ST_INTERSECTS(HG.GEOM, FR.GEOM)
        GROUP BY HG.GID, HG.SHAPE_AREA) AS IQ
WHERE HEXGRID_150.GID = IQ.ID;


-- Finding lake protection line ratio value
ALTER TABLE HEXGRID_150
ADD COLUMN LAKE_PROTECTION_LINE_RATIO
NUMERIC NOT NULL DEFAULT 1;

UPDATE HEXGRID_150
    SET LAKE_PROTECTION_LINE_RATIO = IQ.PRCNT
    FROM (    SELECT     HG.GID ID,
            1 - ROUND(CAST(FLOAT8(ST_AREA(ST_UNION(ST_INTERSECTION(MVLPL.GEOM, HG.GEOM))) / HG.SHAPE_AREA) AS NUMERIC), 6) PRCNT
        FROM HEXGRID_150 HG
            JOIN MV_LAKE_PROTECTION_LINE MVLPL
                ON ST_INTERSECTS(HG.GEOM, MVLPL.GEOM)
        GROUP BY HG.GID, HG.SHAPE_AREA) AS IQ
WHERE HEXGRID_150.GID = IQ.ID;


-- Finding lake ratio value
ALTER TABLE HEXGRID_150
ADD COLUMN LAKES_RATIO
NUMERIC NOT NULL DEFAULT 1;

UPDATE HEXGRID_150
    SET LAKES_RATIO = IQ.PRCNT
    FROM (    SELECT     HG.GID ID,
            1 - ROUND(CAST(FLOAT8(ST_AREA(ST_UNION(ST_INTERSECTION(LAKES.GEOM, HG.GEOM))) / HG.SHAPE_AREA) AS NUMERIC), 6) PRCNT
        FROM HEXGRID_150 HG
            JOIN LAKES
                ON ST_INTERSECTS(HG.GEOM, LAKES.GEOM)
        GROUP BY HG.GID, HG.SHAPE_AREA) AS IQ
WHERE HEXGRID_150.GID = IQ.ID;


-- Finding lowlands protection line ratio value
ALTER TABLE HEXGRID_150
ADD COLUMN LOWLANDS_RATIO
NUMERIC NOT NULL DEFAULT 1;

UPDATE HEXGRID_150
    SET LOWLANDS_RATIO = IQ.PRCNT
    FROM (    SELECT     HG.GID ID,
            1 - ROUND(CAST(FLOAT8(ST_AREA(ST_UNION(ST_INTERSECTION(MV_LOWLANDS.GEOM, HG.GEOM))) / HG.SHAPE_AREA) AS NUMERIC), 6) PRCNT
        FROM HEXGRID_150 HG
            JOIN MV_LOWLANDS
                ON ST_INTERSECTS(HG.GEOM, MV_LOWLANDS.GEOM)
        GROUP BY HG.GID, HG.SHAPE_AREA) AS IQ
WHERE HEXGRID_150.GID = IQ.ID;


--TODO 0 lines???
-- Finding natural bird protection ratio value
ALTER TABLE HEXGRID_150
ADD COLUMN NATURAL_BIRD_PROTECTION_RATIO
NUMERIC NOT NULL DEFAULT 1;

UPDATE HEXGRID_150
    SET NATURAL_BIRD_PROTECTION_RATIO = IQ.PRCNT
    FROM (    SELECT     HG.GID ID,
            1 - ROUND(CAST(FLOAT8(ST_AREA(ST_UNION(ST_INTERSECTION(NBP.GEOM, HG.GEOM))) / HG.SHAPE_AREA) AS NUMERIC), 6) PRCNT
        FROM HEXGRID_150 HG
            JOIN NATURA2000_BIRD_PROTECTION NBP
                ON ST_INTERSECTS(HG.GEOM, NBP.GEOM)
        GROUP BY HG.GID, HG.SHAPE_AREA) AS IQ
WHERE HEXGRID_150.GID = IQ.ID;


-- Finding natural habitat ratio value
ALTER TABLE HEXGRID_150
ADD COLUMN NATURAL_HABITAT_RATIO
NUMERIC NOT NULL DEFAULT 1;

UPDATE HEXGRID_150
    SET NATURAL_HABITAT_RATIO = IQ.PRCNT
    FROM (    SELECT     HG.GID ID,
            1 - ROUND(CAST(FLOAT8(ST_AREA(ST_UNION(ST_INTERSECTION(NH.GEOM, HG.GEOM))) / HG.SHAPE_AREA) AS NUMERIC), 6) PRCNT
        FROM HEXGRID_150 HG
            JOIN NATURA2000_HABITAT NH
                ON ST_INTERSECTS(HG.GEOM, NH.GEOM)
        GROUP BY HG.GID, HG.SHAPE_AREA) AS IQ
WHERE HEXGRID_150.GID = IQ.ID;


-- Finding nature and wildlife sanctuary value
ALTER TABLE HEXGRID_150
ADD COLUMN NATURE_AND_WILDLIFE_SANCTUARY_RATIO
NUMERIC NOT NULL DEFAULT 1;

UPDATE HEXGRID_150
    SET NATURE_AND_WILDLIFE_SANCTUARY_RATIO = IQ.PRCNT
    FROM (    SELECT     HG.GID ID,
            1 - ROUND(CAST(FLOAT8(ST_AREA(ST_UNION(ST_INTERSECTION(NWS.GEOM, HG.GEOM))) / HG.SHAPE_AREA) AS NUMERIC), 6) PRCNT
        FROM HEXGRID_150 HG
            JOIN NATURE_AND_WILDLIFE_SANCTUARY NWS
                ON ST_INTERSECTS(HG.GEOM, NWS.GEOM)
        GROUP BY HG.GID, HG.SHAPE_AREA) AS IQ
WHERE HEXGRID_150.GID = IQ.ID;


--TODO 0 lines??
-- Finding nature registration value
ALTER TABLE HEXGRID_150
ADD COLUMN NATURE_REGISTRATION_RATIO
NUMERIC NOT NULL DEFAULT 1;

UPDATE HEXGRID_150
    SET NATURE_REGISTRATION_RATIO = IQ.PRCNT
    FROM (    SELECT     HG.GID ID,
            1 - ROUND(CAST(FLOAT8(ST_AREA(ST_UNION(ST_INTERSECTION(NR.GEOM, HG.GEOM))) / HG.SHAPE_AREA) AS NUMERIC), 6) PRCNT
        FROM HEXGRID_150 HG
            JOIN NATURE_REGISTRATION NR
                ON ST_INTERSECTS(HG.GEOM, NR.GEOM)
        GROUP BY HG.GID, HG.SHAPE_AREA) AS IQ
WHERE HEXGRID_150.GID = IQ.ID;


-- Finding protected ancient sites value
ALTER TABLE HEXGRID_150
ADD COLUMN PROTECTED_ANCIENT_SITES_RATIO
NUMERIC NOT NULL DEFAULT 1;

UPDATE HEXGRID_150
    SET PROTECTED_ANCIENT_SITES_RATIO = IQ.PRCNT
    FROM (    SELECT     HG.GID ID,
            1 - ROUND(CAST(FLOAT8(ST_AREA(ST_UNION(ST_INTERSECTION(PAS.GEOM, HG.GEOM))) / HG.SHAPE_AREA) AS NUMERIC), 6) PRCNT
        FROM HEXGRID_150 HG
            JOIN PROTECTED_ANCIENT_SITES PAS
                ON ST_INTERSECTS(HG.GEOM, PAS.GEOM)
        GROUP BY HG.GID, HG.SHAPE_AREA) AS IQ
WHERE HEXGRID_150.GID = IQ.ID;


-- Finding protected nature types value
ALTER TABLE HEXGRID_150
ADD COLUMN PROTECTED_NATURE_TYPES_RATIO
NUMERIC NOT NULL DEFAULT 1;

UPDATE HEXGRID_150
    SET PROTECTED_NATURE_TYPES_RATIO = IQ.PRCNT
    FROM (    SELECT     HG.GID ID,
            1 - ROUND(CAST(FLOAT8(ST_AREA(ST_UNION(ST_INTERSECTION(PNT.GEOM, HG.GEOM))) / HG.SHAPE_AREA) AS NUMERIC), 6) PRCNT
        FROM HEXGRID_150 HG
            JOIN PROTECTED_NATURE_TYPES PNT
                ON ST_INTERSECTS(HG.GEOM, PNT.GEOM)
        GROUP BY HG.GID, HG.SHAPE_AREA) AS IQ
WHERE HEXGRID_150.GID = IQ.ID;


-- Finding protected earth and stone dikes values
ALTER TABLE HEXGRID_150
ADD COLUMN PROTECTED_EARTH_STONE_DIKES_RATIO
NUMERIC NOT NULL DEFAULT 1;

UPDATE HEXGRID_150
    SET PROTECTED_EARTH_STONE_DIKES_RATIO = IQ.PRCNT
    FROM (    SELECT     HG.GID ID,
            1 - ROUND(CAST(FLOAT8(ST_AREA(ST_UNION(ST_INTERSECTION(MVPSED.GEOM, HG.GEOM))) / HG.SHAPE_AREA) AS NUMERIC), 6) PRCNT
        FROM HEXGRID_150 HG
            JOIN MV_PROTECTED_STONE_AND_EARTH_DIKES MVPSED
                ON ST_INTERSECTS(HG.GEOM, MVPSED.GEOM)
        GROUP BY HG.GID, HG.SHAPE_AREA) AS IQ
WHERE HEXGRID_150.GID = IQ.ID;


-- Finding protected water streams values
ALTER TABLE HEXGRID_150
ADD COLUMN PROTECTED_WATER_STREAMS_RATIO
NUMERIC NOT NULL DEFAULT 1;

UPDATE HEXGRID_150
    SET PROTECTED_WATER_STREAMS_RATIO = IQ.PRCNT
    FROM (    SELECT     HG.GID ID,
            1 - ROUND(CAST(FLOAT8(ST_AREA(ST_UNION(ST_INTERSECTION(PWS.GEOM, HG.GEOM))) / HG.SHAPE_AREA) AS NUMERIC), 6) PRCNT
        FROM HEXGRID_150 HG
            JOIN PROTECTED_WATER_STREAMS PWS
                ON ST_INTERSECTS(HG.GEOM, PWS.GEOM)
        GROUP BY HG.GID, HG.SHAPE_AREA) AS IQ
WHERE HEXGRID_150.GID = IQ.ID;


--TODO 0 lines
-- Finding ramsar area values
ALTER TABLE HEXGRID_150
ADD COLUMN RAMSAR_AREA_RATIO
NUMERIC NOT NULL DEFAULT 1;

UPDATE HEXGRID_150
    SET RAMSAR_AREA_RATIO = IQ.PRCNT
    FROM (    SELECT     HG.GID ID,
            1 - ROUND(CAST(FLOAT8(ST_AREA(ST_UNION(ST_INTERSECTION(RA.GEOM, HG.GEOM))) / HG.SHAPE_AREA) AS NUMERIC), 6) PRCNT
        FROM HEXGRID_150 HG
            JOIN RAMSAR_AREA RA
                ON ST_INTERSECTS(HG.GEOM, RA.GEOM)
        GROUP BY HG.GID, HG.SHAPE_AREA) AS IQ
WHERE HEXGRID_150.GID = IQ.ID;


-- Finding raw material sites values
ALTER TABLE HEXGRID_150
ADD COLUMN RAW_MATERIAL_SITES_RATIO
NUMERIC NOT NULL DEFAULT 1;

UPDATE HEXGRID_150
    SET RAW_MATERIAL_SITES_RATIO = IQ.PRCNT
    FROM (    SELECT     HG.GID ID,
            1 - ROUND(CAST(FLOAT8(ST_AREA(ST_UNION(ST_INTERSECTION(MVRMS.GEOM, HG.GEOM))) / HG.SHAPE_AREA) AS NUMERIC), 6) PRCNT
        FROM HEXGRID_150 HG
            JOIN MV_RAW_MATERIAL_SITES MVRMS
                ON ST_INTERSECTS(HG.GEOM, MVRMS.GEOM)
        GROUP BY HG.GID, HG.SHAPE_AREA) AS IQ
WHERE HEXGRID_150.GID = IQ.ID;


-- Finding roadsides values
ALTER TABLE HEXGRID_150
ADD COLUMN ROADSIDES_RATIO
NUMERIC NOT NULL DEFAULT 1;

UPDATE HEXGRID_150
    SET ROADSIDES_RATIO = IQ.PRCNT
    FROM (    SELECT     HG.GID ID,
            1 - ROUND(CAST(FLOAT8(ST_AREA(ST_UNION(ST_INTERSECTION(ROADSIDES.GEOM, HG.GEOM))) / HG.SHAPE_AREA) AS NUMERIC), 6) PRCNT
        FROM HEXGRID_150 HG
            JOIN ROADSIDES
                ON ST_INTERSECTS(HG.GEOM, ROADSIDES.GEOM)
        GROUP BY HG.GID, HG.SHAPE_AREA) AS IQ
WHERE HEXGRID_150.GID = IQ.ID;


-- Finding SFL areas values
ALTER TABLE HEXGRID_150
ADD COLUMN SFL_AREAS_RATIO
NUMERIC NOT NULL DEFAULT 1;

UPDATE HEXGRID_150
    SET SFL_AREAS_RATIO = IQ.PRCNT
    FROM (    SELECT     HG.GID ID,
            1 - ROUND(CAST(FLOAT8(ST_AREA(ST_UNION(ST_INTERSECTION(SFLA.GEOM, HG.GEOM))) / HG.SHAPE_AREA) AS NUMERIC), 6) PRCNT
        FROM HEXGRID_150 HG
            JOIN SFL_AREAS SFLA
                ON ST_INTERSECTS(HG.GEOM, SFLA.GEOM)
        GROUP BY HG.GID, HG.SHAPE_AREA) AS IQ
WHERE HEXGRID_150.GID = IQ.ID;


-- Finding stream protection line values
ALTER TABLE HEXGRID_150
ADD COLUMN STREAM_PROTECTION_LINE_RATIO
NUMERIC NOT NULL DEFAULT 1;

UPDATE HEXGRID_150
    SET STREAM_PROTECTION_LINE_RATIO = IQ.PRCNT
    FROM (    SELECT     HG.GID ID,
            1 - ROUND(CAST(FLOAT8(ST_AREA(ST_UNION(ST_INTERSECTION(MVSPL.GEOM, HG.GEOM))) / HG.SHAPE_AREA) AS NUMERIC), 6) PRCNT
        FROM HEXGRID_150 HG
            JOIN MV_STREAM_PROTECTION_LINE MVSPL
                ON ST_INTERSECTS(HG.GEOM, MVSPL.GEOM)
        GROUP BY HG.GID, HG.SHAPE_AREA) AS IQ
WHERE HEXGRID_150.GID = IQ.ID;


-- Finding technical areas values
ALTER TABLE HEXGRID_150
ADD COLUMN TECHNICAL_AREAS_RATIO
NUMERIC NOT NULL DEFAULT 1;

UPDATE HEXGRID_150
    SET TECHNICAL_AREAS_RATIO = IQ.PRCNT
    FROM (    SELECT     HG.GID ID,
            1 - ROUND(CAST(FLOAT8(ST_AREA(ST_UNION(ST_INTERSECTION(MVTA.GEOM, HG.GEOM))) / HG.SHAPE_AREA) AS NUMERIC), 6) PRCNT
        FROM HEXGRID_150 HG
            JOIN MV_TECHNICAL_AREAS MVTA
                ON ST_INTERSECTS(HG.GEOM, MVTA.GEOM)
        GROUP BY HG.GID, HG.SHAPE_AREA) AS IQ
WHERE HEXGRID_150.GID = IQ.ID;


-- Finding v1 soil pollution values
ALTER TABLE HEXGRID_150
ADD COLUMN V1_SOIL_POLUTION_RATIO
NUMERIC NOT NULL DEFAULT 1;

UPDATE HEXGRID_150
    SET V1_SOIL_POLUTION_RATIO = IQ.PRCNT
    FROM (    SELECT     HG.GID ID,
            1 - ROUND(CAST(FLOAT8(ST_AREA(ST_UNION(ST_INTERSECTION(MVSP.GEOM, HG.GEOM))) / HG.SHAPE_AREA) AS NUMERIC), 6) PRCNT
        FROM HEXGRID_150 HG
            JOIN MV_V1_SOIL_POLUTION MVSP
                ON ST_INTERSECTS(HG.GEOM, MVSP.GEOM)
        GROUP BY HG.GID, HG.SHAPE_AREA) AS IQ
WHERE HEXGRID_150.GID = IQ.ID;


-- Finding v2 soil pollution values
ALTER TABLE HEXGRID_150
ADD COLUMN V2_SOIL_POLUTION_RATIO
NUMERIC NOT NULL DEFAULT 1;

UPDATE HEXGRID_150
    SET V2_SOIL_POLUTION_RATIO = IQ.PRCNT
    FROM (    SELECT     HG.GID ID,
            1 - ROUND(CAST(FLOAT8(ST_AREA(ST_UNION(ST_INTERSECTION(MVSP.GEOM, HG.GEOM))) / HG.SHAPE_AREA) AS NUMERIC), 6) PRCNT
        FROM HEXGRID_150 HG
            JOIN MV_V2_SOIL_POLUTION MVSP
                ON ST_INTERSECTS(HG.GEOM, MVSP.GEOM)
        GROUP BY HG.GID, HG.SHAPE_AREA) AS IQ
WHERE HEXGRID_150.GID = IQ.ID;


-- Finding wetlands values
ALTER TABLE HEXGRID_150
ADD COLUMN WETLANDS_RATIO
NUMERIC NOT NULL DEFAULT 1;

UPDATE HEXGRID_150
    SET WETLANDS_RATIO = IQ.PRCNT
    FROM (    SELECT     HG.GID ID,
            1 - ROUND(CAST(FLOAT8(ST_AREA(ST_UNION(ST_INTERSECTION(MV_WETLANDS.GEOM, HG.GEOM))) / HG.SHAPE_AREA) AS NUMERIC), 6) PRCNT
        FROM HEXGRID_150 HG
            JOIN MV_WETLANDS
                ON ST_INTERSECTS(HG.GEOM, MV_WETLANDS.GEOM)
        GROUP BY HG.GID, HG.SHAPE_AREA) AS IQ
WHERE HEXGRID_150.GID = IQ.ID;


-- Finding forest protection line ratio value
ALTER TABLE HEXGRID_150
ADD COLUMN FOREST_PROTECTION_LINE_RATIO
NUMERIC NOT NULL DEFAULT 1;

UPDATE HEXGRID_150
    SET FOREST_PROTECTION_LINE_RATIO = IQ.PRCNT
    FROM (    SELECT     HG.GID ID,
            1 - ROUND(CAST(FLOAT8(ST_AREA(ST_UNION(ST_INTERSECTION(MVFPL.GEOM, HG.GEOM))) / HG.SHAPE_AREA) AS NUMERIC), 6) PRCNT
        FROM HEXGRID_150 HG
            JOIN MV_FOREST_PROTECTION_LINE MVFPL
                ON ST_INTERSECTS(HG.GEOM, MVFPL.GEOM)
        GROUP BY HG.GID, HG.SHAPE_AREA) AS IQ
WHERE HEXGRID_150.GID = IQ.ID;

-- FINDING DISTRICT PLAN RATIO VALUES
ALTER TABLE HEXGRID_150
ADD COLUMN DISTRICT_PLAN_RATIO
NUMERIC NOT NULL DEFAULT 1;

UPDATE HEXGRID_150
    SET DISTRICT_PLAN_RATIO = IQ.PRCNT
    FROM (    SELECT     HG.GID ID,
        1 - ROUND(CAST(FLOAT8(ST_AREA(ST_UNION(ST_INTERSECTION(MVDP.GEOM, HG.GEOM))) / HG.SHAPE_AREA) AS NUMERIC), 6) PRCNT
        FROM HEXGRID_150 HG
            JOIN MV_DISTRICT_PLAN MVDP
                ON ST_INTERSECTS(HG.GEOM, MVDP.GEOM)
        GROUP BY HG.GID, HG.SHAPE_AREA) AS IQ
WHERE HEXGRID_150.GID = IQ.ID;

-- Create the final layer view
CREATE VIEW FINAL_LAYER
AS
(
    SELECT HG.GID AS GID,
        HG.SHAPE_AREA AS SHAPE_AREA,
        HG.GEOM AS GEOM,

        HG.BUILDING_RATIO * CFG.RESTRICTIVE_MULTIPLIER AS BUILDING_RATIO,
        HG.BURIAL_AREA_RATIO  * CFG.RESTRICTIVE_MULTIPLIER AS BURIAL_AREA_RATIO,
        HG.CONSERVATION_RATIO * CFG.RESTRICTIVE_MULTIPLIER AS CONSERVATION_RATIO,
        HG.DUNE_CONSERVATION_RATIO * CFG.RESTRICTIVE_MULTIPLIER AS DUNE_CONSERVATION_RATIO,
        HG.EDGE_WATER_STREAM_RATIO * CFG.RESTRICTIVE_MULTIPLIER AS EDGE_WATER_STREAM_RATIO,
        HG.FOREST_RATIO * CFG.RESTRICTIVE_MULTIPLIER AS FOREST_RATIO,
        HG.LAKES_RATIO * CFG.RESTRICTIVE_MULTIPLIER AS LAKES_RATIO,
        HG.NATURAL_BIRD_PROTECTION_RATIO * CFG.RESTRICTIVE_MULTIPLIER AS NATURAL_BIRD_PROTECTION_RATIO,
        HG.NATURAL_HABITAT_RATIO * CFG.RESTRICTIVE_MULTIPLIER AS NATURAL_HABITAT_RATIO,
        HG.NATURE_AND_WILDLIFE_SANCTUARY_RATIO * CFG.RESTRICTIVE_MULTIPLIER AS NATURE_AND_WILDLIFE_SANCTUARY_RATIO,
        HG.NATURE_REGISTRATION_RATIO * CFG.RESTRICTIVE_MULTIPLIER AS NATURE_REGISTRATION_RATIO,
        HG.PROTECTED_ANCIENT_SITES_RATIO * CFG.RESTRICTIVE_MULTIPLIER AS PROTECTED_ANCIENT_SITES_RATIO,
        HG.PROTECTED_NATURE_TYPES_RATIO * CFG.RESTRICTIVE_MULTIPLIER AS PROTECTED_NATURE_TYPES_RATIO,
        HG.PROTECTED_WATER_STREAMS_RATIO * CFG.RESTRICTIVE_MULTIPLIER AS PROTECTED_WATER_STREAMS_RATIO,
        HG.RAMSAR_AREA_RATIO * CFG.RESTRICTIVE_MULTIPLIER AS RAMSAR_AREA_RATIO,
        HG.ROADSIDES_RATIO * CFG.RESTRICTIVE_MULTIPLIER AS ROADSIDES_RATIO,
        HG.STATE_ROAD_RATIO * CFG.RESTRICTIVE_MULTIPLIER AS STATE_ROAD_RATIO,
        HG.RAILROAD_RATIO * CFG.RESTRICTIVE_MULTIPLIER AS RAILROAD_RATIO,
        HG.WIND_TURBINE_RATIO * CFG.RESTRICTIVE_MULTIPLIER AS WIND_TURBINE_RATIO,
        HG.FOREST_RESERVE_RATIO * CFG.RESTRICTIVE_MULTIPLIER AS FOREST_RESERVE_RATIO,

        HG.CHURCH_PROTECTION_LINE_RATIO * CFG.UNRECEPTIVE_MULTIPLIER AS CHURCH_PROTECTION_LINE_RATIO,
        HG.COAST_LINE_ZONE_RATIO * CFG.UNRECEPTIVE_MULTIPLIER AS COAST_LINE_ZONE_RATIO,
        HG.FOREST_PROTECTION_LINE_RATIO * CFG.UNRECEPTIVE_MULTIPLIER AS FOREST_PROTECTION_LINE_RATIO,
        HG.LAKE_PROTECTION_LINE_RATIO * CFG.UNRECEPTIVE_MULTIPLIER AS LAKE_PROTECTION_LINE_RATIO,
        HG.LOWLANDS_RATIO * CFG.UNRECEPTIVE_MULTIPLIER AS LOWLANDS_RATIO,
        HG.PROTECTED_EARTH_STONE_DIKES_RATIO * CFG.UNRECEPTIVE_MULTIPLIER AS PROTECTED_EARTH_STONE_DIKES_RATIO,
        HG.STREAM_PROTECTION_LINE_RATIO * CFG.UNRECEPTIVE_MULTIPLIER AS STREAM_PROTECTION_LINE_RATIO,
        HG.V2_SOIL_POLUTION_RATIO * CFG.UNRECEPTIVE_MULTIPLIER AS V2_SOIL_POLUTION_RATIO,
        HG.WETLANDS_RATIO * CFG.UNRECEPTIVE_MULTIPLIER AS WETLANDS_RATIO,
        HG.BEACH_PROTECTION_RATIO * CFG.UNRECEPTIVE_MULTIPLIER AS BEACH_PROTECTION_RATIO,
        HG.WIND_TURBINE_SITE_RATIO * CFG.UNRECEPTIVE_MULTIPLIER AS WIND_TURBINE_SITE_RATIO,
        HG.MUNICIPALITY_ROAD_RATIO * CFG.UNRECEPTIVE_MULTIPLIER AS MUNICIPALITY_ROAD_RATIO,
        HG.RAW_MATERIAL_SITES_RATIO * CFG.UNRECEPTIVE_MULTIPLIER AS RAW_MATERIAL_SITES_RATIO,

        HG.DISTRICT_PLAN_RATIO * CFG.LIMITING_MULTIPLIER AS DISTRICT_PLAN_RATIO,
        HG.V1_SOIL_POLUTION_RATIO * CFG.LIMITING_MULTIPLIER AS V1_SOIL_POLUTION_RATIO,
        HG.DRINKING_WATER_INTEREST_RATIO * CFG.LIMITING_MULTIPLIER AS DRINKING_WATER_INTEREST_RATIO,

        HG.TECHNICAL_AREAS_RATIO * CFG.ADVANTAGEOUS_MULTIPLIER AS TECHNICAL_AREAS_RATIO
        
    FROM HEXGRID_150 HG
        JOIN V_CONFIG CFG
            ON CFG.C_ID = 1
            
    ORDER BY HG.GID ASC
);